spring:
  datasource:
    url: jdbc:h2:mem:fleetops_core;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;NON_KEYWORDS=USER
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: fleet-core-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.fleetops.core.kafka.event"


    flyway:
      enabled: false
      locations: classpath:db/migration
      baseline-on-migrate: true


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
