CREATE TABLE vehicles (
    id                      BIGSERIAL        PRIMARY KEY,
    company_id              BIGINT           NOT NULL REFERENCES companies(id),
    make                    VARCHAR(100)     NOT NULL,
    model                   VARCHAR(100)     NOT NULL,
    plate_number            VARCHAR(20)      NOT NULL UNIQUE,
    current_mileage         DOUBLE PRECISION NOT NULL DEFAULT 0,
    milestone_interval      DOUBLE PRECISION NOT NULL,
    purchase_price          DECIMAL(15,2),
    purchase_date           DATE,
    total_maintenance_spend DECIMAL(15,2)    NOT NULL DEFAULT 0,
    breakdown_count         INT              NOT NULL DEFAULT 0,
    health_score            DOUBLE PRECISION,
    health_grade            VARCHAR(20),
    sell_recommendation     TEXT,
    health_computed_at      TIMESTAMP,
    lifecycle_percentage    DOUBLE PRECISION DEFAULT 0,
    marked_for_sale         BOOLEAN          DEFAULT FALSE,
    max_mileage             DOUBLE PRECISION DEFAULT 300000,
    max_trips               INT              DEFAULT 500,
    max_maintenance_rounds  INT              DEFAULT 30,
    status                  VARCHAR(50)      NOT NULL DEFAULT 'AVAILABLE',
    registered_at           TIMESTAMP        NOT NULL DEFAULT NOW()
);